# -*- coding: utf-8 -*-

import os, sys

from  django.shortcuts  import  render
from  django.http  import  HttpResponse

def journal_list(request):
        journals  =  (
            {'id':  1,
            'student_name':  u'Віталій Подоба',
            'day1': 0,
            'day2': 1,
            'day3': 1,
            'day4': 1,
            'day5': 1,
            'day6': 1,
            'day7': 0,
            'day8': 8,
            'day9': 0,
            'day10': 0,
            'day11': 0,
            'day12': 0,
            'day13': 0,
            'day14': 0,
            'day15': 0,
            'day16': 0,
            'day17': 0,
            'day18': 0,
            'day19': 0,
            'day20': 0,
            'day21': 0,
            'day22': 0,
            'day23': 0,
            'day24': 0,
            'day25': 0,
            'day26': 0,
            'day27': 0,
            'day28': 0,
            'day29': 0,
            'day30': 0,
            'day31': 0  },
            {'id':  2,
            'student_name':  u'Андрій Корост',
            'day1': 0,
            'day2': 0,
            'day3': 1,
            'day4': 1,
            'day5': 1,
            'day6': 1,
            'day7': 0,
            'day8': 0,
            'day9': 0,
            'day10': 1,
            'day11': 0,
            'day12': 0,
            'day13': 0,
            'day14': 0,
            'day15': 0,
            'day16': 0,
            'day17': 0,
            'day18': 0,
            'day19': 0,
            'day20': 0,
            'day21': 0,
            'day22': 0,
            'day23': 0,
            'day24': 0,
            'day25': 0,
            'day26': 0,
            'day27': 0,
            'day28': 0,
            'day29': 0,
            'day30': 0,
            'day31': 0  },
            {'id':  3,
            'student_name':  u'Ростислав Боднар',            
            'day1': 0,
            'day2': 0,
            'day3': 0,
            'day4': 1,
            'day5': 1,
            'day6': 0,
            'day7': 0,
            'day8': 0,
            'day9': 1,
            'day10': 0,
            'day11': 0,
            'day12': 0,
            'day13': 0,
            'day14': 0,
            'day15': 0,
            'day16': 0,
            'day17': 0,
            'day18': 0,
            'day19': 0,
            'day20': 0,
            'day21': 0,
            'day22': 0,
            'day23': 0,
            'day24': 0,
            'day25': 0,
            'day26': 0,
            'day27': 0,
            'day28': 0,
            'day29': 0,
            'day30': 0,
            'day31': 0  },)
        return  render(request,  'students/journal_list.html', {'journals':  journals})